fail fast

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,8 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+# fail fast
+set -o errexit
+set -o pipefail
 
 function indent() {
   c='s/^/       /'
